version: '3.9'

networks:
  task_network:
    driver: bridge

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - task_network  
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - task_network   
    volumes:
      - ./frontend:/frontend         
    command: npm run dev -- --host
