
name: task-tracker pipeline

on:
    push:                   
      branches:
        - day6 

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: set up python
            uses: actions/setup-python@v5
            with:
                python-version: '3.11'

          - name: install dependencies
            run: |
                cd backend
                pip install -r requirements.txt

    test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: install dependencies
          run: |
              cd backend
              pip install -r requirements.txt  
         
        - name: Start Backend App
          run: |
              cd backend
              nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
              sleep 10
        
        - name: Health Check Application
          run: |
              curl --fail http://localhost:8000/health || exit 1      
              
        - name: Run Tests
          run: |
            cd backend
            pytest      

        
        